# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem, e.g., npm, bundler, pip, etc.
    directory: "frontend" # Location of package manifests, e.g., where your package.json or requirements.txt is located
    schedule:
      interval: "weekly"
